set MATLAB=C:\Program Files\MATLAB\R2015b
"C:\PROGRA~1\MATLAB\R2015b\bin\win64\gmake" -f WaterTankSysControl2018.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DON_TARGET_WAIT_FOR_START=1"
